DOMAIN = "https://aldebaran.ru"
TOKEN = "Bot TOKEN"
START_MESSAGE = "Для начала работы введите название книги или имя автора"
UNKNOWN_COMMAND_MESSAGE = "Я не смог распознать введенную команду"
GET_BOOK_FAIL_MESSAGE = "Не удалось получить информацию о книге"
DOWNLOAD_FAIL_MESSAGE = "Не удалось скачать книгу"
TEMP_DIR = "temp\\"
BOOKS_ON_PAGE = 6
INLINE_BOOKS_SEARCH_QUANTITY = 5
BOOKS_ON_DOMAIN_PAGE = 20
INLINE_CACHE_TIME = 300
INLINE_RAW_WIDTH = 3
BOT_STORAGE_CHANNEL_ID = "Channel id where bot will send documents to cache them"
CAPTION_LENGTH_LOCK = 1024 # Must be in range (0-1024)
